config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"
  get '/about' =>"public/homes#about"
  resources :items, only: [:index,:show]


  scope module: :public do
    # 顧客側のマイページ,登録情報編集&更新
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    # 顧客側の退会確認画面,退会処理
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    # 顧客側のカート画面
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]


    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :orders, only: [:new, :create, :index, :show]

  end



  namespace :admin do
    root :to => "homes#top"
    resources :items
    resources :genres
    resources :customers, only: [:index, :edit, :update, :show]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :items, through: :order_details

  validates :unit_price, presence: true , length: { minimum: 1 }

  has_one_attached :item_image


  def get_item_image
    (item_image.attached?) ? item_image : 'no_image.jpg'
  end

  def add_tax_price
        (self.unit_price * 1.08).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  # ↓管理者以外はトップページにリダイレクトさせるコード
  before_action :authenticate_admin!

  def index
    # ↓ページネーション
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品を更新しました。"
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end



  private

  def item_params
    params.require(:item).permit(:name, :introduction, :unit_price, :is_on_sale, :item_image, :genre_id)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def converting_to_jpy(unit_price)
    "#{unit_price.to_s(:delimited, delimiter: ',')}円"
  end

end

app/views/admin/items/edit.html.erb
<div class="container">
  <h5 class="col-md-7 mb-5 mt-5">
      <span class="py-2 px-4 bg-ligh alert-secondary">商品編集</span>
    </h5>
  <div class="row">
    <div class="col-10 offset-2">
<!--↓10/21エラー文の表示、テンプレート化すると思ったので一旦、コメントアウトしています（しま）-->
        <!--<% if @item.errors.any? %>-->
        <!--<h3><%= @item.errors.count %>error prohibited this obj from being saved:</h3>-->
        <!--<ul>-->
        <!--  <% @item.errors.full_messages.each do |message| %>-->
        <!--  <li><%= message %></li>-->
        <!--  <% end %>-->
        <!--</ul>-->
        <!--<% end %>-->

      <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |item| %>
        <table class="ml-4">
            <tr>
              <td>
                <%= item.label  "商品画像", style: "margin-right:70px;"%>
              </td>
              <td>
                 <%= item.file_field :item_image, accept: "image/*", class: "form-control-file" %>
              </td>
            </tr>
            <tr>
              <td>
                <%= item.label "商品名"%>
              </td>
              <td>
                 <%= item.text_field :name, class: "form-control"%>
              </td>
            </tr>
            <tr>
              <td valign="top">
                <%= item.label "商品説明 "%>
              </td>
              <td>
                <%= item.text_area :introduction, class: "form-control", :size=>"42x8" %>
              </td>
            </tr>
            <tr>
              <td>
                <%= item.label "ジャンル"%>
              </td>
              <td>
                <%= item.collection_select :genre_id, Genre.all, :id, :name ,:size=>"40", class: 'form-control'%>
              </td>
            </tr>
            <tr>
              <td>
                <%= item.label "税抜き価格"%>
              </td>
              <td>
                <%= item.text_field :unit_price, class: "form-control" %>
              </td>
              <td>円</td>
            </tr>
            <tr>
              <td>
                <%= item.label "販売ステータス"%>
              </td>
              <td align="center">
                <label><%= item.radio_button :is_on_sale, :true %>販売中</label>
                <label><%= item.radio_button :is_on_sale, :false %>販売停止中</label>
              </td>
            </tr>
            <tr>
              <td></td>
              <td align="center">
                <%= item.submit '変更を保存', class: "btn btn-success" %>
              </td>
            </tr>
          </table>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row col-12'>
      <div class="col-md-12 d-flex bd-highlight mt-3 ">
        <div class='col-md-11'>
          <h5 class="p-2 bd-highlight"><span class="py-2 px-4 bg-ligh alert-secondary">商品一覧</span></h5>
        </div>
        
        <%= link_to new_admin_item_path do %>
              <i class="fa fa-plus-circle fa-3x" style="color: #d3d3d3;"></i>
            <% end %>
　　    
　　　</div>
　</div>
　<div class='col-md-10 ml-5'>
　  
　  <table class="table table-hover table-inverse" >
      <thead class="thead-light">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </thead>
    <% @items.each do |item| %>
      <tbody>
          <td><%= item.id %></td>
          <td><%= link_to item.name,admin_item_path(item.id) ,class:"text-dark border-bottom border-dark"%></td>
          <td><%= converting_to_jpy(item.unit_price) %></td>
          <td><%= item.genre.name %></td>
          <% if item.is_on_sale? %>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="text-black-50">販売停止中</td>
          <% end %>
        </tbody>
      <% end %>
      </table>
　</div>
  <div class="row justify-content-center mt-3">
    <div class='mr-5'>
       <!--↓ページネーションの記載-->
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  <h5 class="col-md-7 mb-5 mt-5 offset-2">
      <span class="py-2 px-4 bg-ligh alert-secondary">商品新規登録</span>
    </h5>
    <div class="row">
      <div class="col-10 offset-2">
        <!--　　　　　　　　　↓「admin_items_path」を記入しないとitem_pathを参照してしまうので記入　-->
        <%= form_with url: admin_items_path, model: @item, local: true do |form| %>
          <table class="ml-4">
            <tr>
              <td>
                <%= form.label "商品画像"%>
              </td>
              <td>
                 <%= form.file_field :item_image, accept: "image/*" %>
              </td>
            </tr>
            <tr>
              <td>
                <%= form.label "商品名"%>
              </td>
              <td>
                 <%= form.text_field :name,placeholder: '商品名', class: "form-control" %>
              </td>
            </tr>
            <tr>
              <td valign="top">
                <%= form.label "商品説明"%>
              </td>
              <td>
                <%= form.text_area :introduction,placeholder: 'ここに説明文を記述します', class: "form-control", :size=>"42x8" %>
              </td>
            </tr>
            <tr>
              <td>
                <%= form.label "ジャンル"%>
              </td>
              <td>
                <%= form.collection_select :genre_id, Genre.all, :id, :name,
                                       :prompt => "--選択してください--"%>
              </td>
            </tr>
            <tr>
              <td>
                <%= form.label "税抜き価格"%>
              </td>
              <td>
                <%= form.text_field :unit_price,placeholder: '1000', class: "form-control" %>
              </td>
              <td>円</td>
            </tr>
            <tr>
              <td>
                <%= form.label "販売ステータス"%>
              </td>
              <td align="center">
                <label><%= form.radio_button :is_on_sale, :true %> 販売中</label>
                <label><%= form.radio_button :is_on_sale, :false %> 販売停止中</label>
              </td>
            </tr>
            <tr>
              <td></td>
              <td align="center">
                <%= form.submit '新規登録', class: "btn-success btn-lg" %>
              </td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
    <h5 class="col-lg-3 mb-5 mt-3 d-flex justify-content-center">
      <span class="py-2 px-4 bg-ligh alert-secondary">商品詳細</span>
    </h5>
    <div class="row">
      <div class="col-lg-5 d-flex justify-content-center">
        <%= image_tag @item.get_item_image,size: "300x260", class: "img-fluid" %><br>
      </div>
      <div class="col-lg-5 d-flex justify-content-center">
        <table class = "ml-7">
          <body>
            <tr>
              <td>商品名</td>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <td>税込価格<br>(税抜価格)</td>
              <td><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.unit_price %>）円</td>
            </tr>
            <tr>
              <td class='text-nowrap'>販売ステータス　</td>
                <% if @item.is_on_sale? %>
              <td class="text-success">販売中</td>
                <% else %>
              <td class="text-black-50">販売停止中</td>
                <% end %>
            </td>
          </body>
        </table>
      </div>
    </div>
  <div class = "row">
    <div class = "col mt-5">
        <div class="center-block text-center">
      <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success btn-lg" %>
        </div>
    </div>
  </div>
</div>