config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"
  get '/about' =>"public/homes#about"
  resources :items, only: [:index,:show]


  scope module: :public do
    # 顧客側のマイページ,登録情報編集&更新
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    # 顧客側の退会確認画面,退会処理
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    # 顧客側のカート画面
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]


    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :orders, only: [:new, :create, :index, :show]

  end



  namespace :admin do
    root :to => "homes#top"
    resources :items
    resources :genres
    resources :customers, only: [:index, :edit, :update, :show]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :order, dependent: :destroy

  # (10/21 その)バリデーションのmaxlengthはWBSガントチャートの「データ」タブ参考
  # (10/21 その)下記必要最低限のバリデーション、minimumはのちに決めます
  validates :last_name, presence: true , length: { maximum: 8 }
  validates :first_name, presence: true , length: { maximum: 10 }
  validates :last_name_kana, presence: true , length: { maximum: 10 }
  validates :first_name_kana, presence: true , length: { maximum: 20 }
  validates :postcode, presence: true , length: { maximum: 7 }
  validates :telephone_number, presence: true , length: { maximum: 15 }
  validates :address, presence: true , length: { maximum: 161 }
  validates :email, presence: true , length: { maximum: 254 }

  # 姓(last_name)と名(irst_name)を合わせて表示する(顧客一覧画面customers/indexで使用)
  def full_name
    self.last_name + self.first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    # updateの構文：モデルのインスタンス.update(更新データ)
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報が更新されました。"
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :telephone_number, :is_deleted, :email)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-6'>
      <div class="d-flex bd-highlight mb-3 mt-3">
        <h5 class="p-2 bd-highlight">
          <span class="px-3 bg-ligh alert-secondary"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span>
        </h5>
      </div>
    </div>
  </div>
  <div class="container mx-5">
    <div class="col-12">
      <%= form_with url: admin_customer_path(@customer), model: @customer, local: true do |customer| %>
        <div class="form-group">
                <%= customer.label :id, '会員ID', class: "col-sm-2 control-label" %>
                <%= @customer.id %>
              </div>
        <div class="form-group">
                <%= customer.label "氏名", class: "col-sm-2 control-label"%>
                <%= customer.text_field :last_name, class: "mr-5" %>
                  <%= customer.text_field :first_name %>
              </div>
        <div class="form-group">
                <%= customer.label "フリガナ", class: "col-sm-2 control-label"%>
                <%= customer.text_field :last_name_kana, class: "mr-5" %>
                <%= customer.text_field :first_name_kana %>
              </div>
        <div class="form-group">
                <%= customer.label "郵便番号", class: "col-sm-2 control-label" %>
                <%= customer.text_field :postcode, class: "mr-5" %>
              </div>
        <div class="form-group">
                <%= customer.label "住所", class: "col-sm-2 control-label" %>
                <%= customer.text_field :address, class: "mr-5", :size=>"60" %>
              </div>
        <div class="form-group">
                <%= customer.label "電話番号", class: "col-sm-2 control-label" %>
                <%= customer.text_field :telephone_number, class: "mr-5" %>
              </div>
        <div class="form-group">
                <%= customer.label "メールアドレス", class: "col-sm-2 control-label" %>
                <%= customer.text_field :email, class: "mr-5" %>
              </div>
        <div class="form-group">
                <%= customer.label "会員ステータス" , class: "col-sm-2 control-label"%>
                <%= customer.radio_button :is_deleted, :false %>
                <%= customer.label :is_deleted, "有効", value: false %>
                <%= customer.radio_button :is_deleted,  :true %>
                <%= customer.label :is_deleted, "退会", value: true %>
              </div>
        <div class="actions">
                <%= customer.label :"　", class: "col-sm-2 control-label" %>
                <%= customer.submit "変更を保存", class: 'btn btn-success' %>
              </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10'>
      <div class="d-flex bd-highlight mb-3 mt-3 ">
        <h5 class="p-2 bd-highlight"><span class="py-2 px-4 bg-ligh alert-secondary">会員一覧</span></h5>
　　　</div>
　　　<div class='col-md-10 offset-2'>
        <table class="table table-hover table-inverse" >
          <thead class="thead-light">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </thead>
          <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>

          <td>
            <%= link_to  admin_customer_path(customer.id) do %>
              <span class="text-dark border-bottom border-dark">
                <!--# 姓(last_name)と名(irst_name)を合わせて表示する-->
                <%=  customer.full_name %>
              </span>
            <% end %>
          </td>

          <td><%= customer.email %></td>

          <% if customer.is_deleted? %>
            <td class="text-black-50">退会</td>
          <% else %>
            <td class="text-success">有効</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class='mr-5'>
      <!--↓ページネーションの記載-->
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <%= flash[:notice] %>
  <div class='row'>
    <div class='col-6'>
      <div class="d-flex bd-highlight mb-3 mt-3 ">
        <h5 class="p-2 bd-highlight">
          <span class="py-2 px-4 bg-ligh alert-secondary"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span>
        </h5>
　　　</div>
　　　
      <table class="table table-borderless ">
        <tr>
          <td>会員ID</td>
          <td colspan="2"><%= @customer.id %></td>
        </tr>

        <tr>
          <td>氏名</td>
          <td colspan="2"><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>

          <td>フリガナ</td>
          <td colspan="2"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td colspan="2"><%= @customer.postcode %></td>
        </tr>

        <tr>
          <td>住所</td>
          <td colspan="2"><%= @customer.address %></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td colspan="2"><%= @customer.telephone_number %></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td colspan="2"><%= @customer.email %></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
           <% if @customer.is_deleted? %>
              <td class="text-black-50">退会</td>
           <% else %>
              <td class="text-success">有効</td>
           <% end %>
        </tr>

        <tr>
          <td></td>
          <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></td>
          <td><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %></td>
        </tr>

      </table>
    </div>
  </div>
</div>