config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"
  get '/about' =>"public/homes#about"
  resources :items, only: [:index,:show]


  scope module: :public do
    # 顧客側のマイページ,登録情報編集&更新
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    # 顧客側の退会確認画面,退会処理
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    # 顧客側のカート画面
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]


    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :orders, only: [:new, :create, :index, :show]

  end



  namespace :admin do
    root :to => "homes#top"
    resources :items
    resources :genres
    resources :customers, only: [:index, :edit, :update, :show]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :items, through: :order_details

  validates :unit_price, presence: true , length: { minimum: 1 }

  has_one_attached :item_image


  def get_item_image
    (item_image.attached?) ? item_image : 'no_image.jpg'
  end

  def add_tax_price
        (self.unit_price * 1.08).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  # ↓管理者以外はトップページにリダイレクトさせるコード
  before_action :authenticate_admin!

  def index
    # ↓ページネーション
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品を更新しました。"
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end



  private

  def item_params
    params.require(:item).permit(:name, :introduction, :unit_price, :is_on_sale, :item_image, :genre_id)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def converting_to_jpy(unit_price)
    "#{unit_price.to_s(:delimited, delimiter: ',')}円"
  end

end

app/views/items/index.html.erb
<div class='container'>
  <div class='row pt-4'>
    <div class='col-md-12'>
      <h1>商品一覧 <span class='item_count'>(全<%= Item.count %>件)</span></h1>

        <div class='row pt-3 row-eq-height'>
          <% @items.each do |item| %>
            <div class="col-sm-3">
              <div class="img-container">
                <%= link_to item_path(item.id) do %>
                <%= image_tag item.get_item_image, class: "rounded", size: '200x130' %>
                <% end %>
              </div>
              <p class='pt-2 font-weight-bold'>
                <%= item.name %><br>
                ¥ <%= item.add_tax_price.to_s(:delimited) %> (税込)
              </p>
            </div>
          <% end %>
        </div>

        <div class="mt-4">
          <div class="row justify-content-center">
            <%= paginate @items %>
          </div>
        </div>


    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class='container'>
  <div class='row mt-5 pt-5 col-md-12'>
      <div class='col-md-5'>
        <%= image_tag @item.get_item_image, size:'300x220' %>
      </div>
      <div class='col-md-6'>
        <h3 class='font-weight-bold'><%= @item.name %></h3>
        <p><%= @item.introduction %></p>

        <%= form_with model: CartItem, url: cart_items_path, method: :post do |f| %>
        <div class='row col-md-12 pb-3 pt-3'>
          <h3>¥ <%= @item.add_tax_price.to_s(:delimited) %> <span class='tax'>(税込)</span></h3>
          <%= f.hidden_field :item_id, :value => @item.id %>
        </div>

          <% if @item.is_on_sale? %>
            <div class="row col-md-10 mt-3">
             <%= flash[:alert] %>
              <div class='col-5'>
              <%= f.select :amount, *[1..10], { include_blank: '個数選択' }, class: "form-control mb-2", required:"required" %>
              </div>
              <div class='col-3'>
                <%= f.submit "カートに入れる" , class: 'btn btn-success' %>
              </div>
            </div>
          <% else %>
            <div class="row col-md-10 mt-3">
              <div class='col-5'>
                <h3>売切れ</h3>
              </div>
            </div>
          <% end %>

        <% end %>
      </div>
  </div>
</div>