config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"
  get '/about' =>"public/homes#about"
  resources :items, only: [:index,:show]


  scope module: :public do
    # 顧客側のマイページ,登録情報編集&更新
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/infomation' => 'customers#update'
    # 顧客側の退会確認画面,退会処理
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'
    # 顧客側のカート画面
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :create, :destroy]


    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :orders, only: [:new, :create, :index, :show]

  end



  namespace :admin do
    root :to => "homes#top"
    resources :items
    resources :genres
    resources :customers, only: [:index, :edit, :update, :show]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :postcode, presence: true , length: { maximum: 7 }
  validates :address, presence: true , length: { maximum: 161 }
  validates :name, presence: true , length: { maximum: 60 }

  def address_display
  '〒' + postcode + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # consoleからのみ登録可能にするため:registerableを削除（しま）
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  ## 小計を求めるメソッド
  def subtotal
      item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :order, dependent: :destroy

  # (10/21 その)バリデーションのmaxlengthはWBSガントチャートの「データ」タブ参考
  # (10/21 その)下記必要最低限のバリデーション、minimumはのちに決めます
  validates :last_name, presence: true , length: { maximum: 8 }
  validates :first_name, presence: true , length: { maximum: 10 }
  validates :last_name_kana, presence: true , length: { maximum: 10 }
  validates :first_name_kana, presence: true , length: { maximum: 20 }
  validates :postcode, presence: true , length: { maximum: 7 }
  validates :telephone_number, presence: true , length: { maximum: 15 }
  validates :address, presence: true , length: { maximum: 161 }
  validates :email, presence: true , length: { maximum: 254 }

  # 姓(last_name)と名(irst_name)を合わせて表示する(顧客一覧画面customers/indexで使用)
  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :items, through: :order_details

  validates :unit_price, presence: true , length: { minimum: 1 }

  has_one_attached :item_image


  def get_item_image
    (item_image.attached?) ? item_image : 'no_image.jpg'
  end

  def add_tax_price
        (self.unit_price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord


 belongs_to :customer
 has_many :order_details
 has_many :items, through: :order_details


  enum payment_method: { credit_card: 0, transfer: 1}

  enum status: {

     waiting_deposit: 0,
     confirm_deposit: 1,
     in_production: 2,
     preparing_shipment: 3,
     shipped: 4
  }

validates :postcode, presence: true, length: { maximum: 7 }
validates :address, presence: true, length: { maximum: 161 }
validates :name, presence: true, length: { maximum:60 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum product_status: {cannot_make: 0, is_waiting: 1, is_making: 2, completed: 3 }


    ## 小計を求めるメソッド
  def subtotal
      item.add_tax_price*amount
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).order(created_at: "DESC")

  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  # ↓管理者以外はトップページにリダイレクトさせるコード
  before_action :authenticate_admin!

  def index
    # ↓ページネーション
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品を更新しました。"
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end



  private

  def item_params
    params.require(:item).permit(:name, :introduction, :unit_price, :is_on_sale, :item_image, :genre_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   

  private

  def after_sign_in_path_for(resource)
    # （10/20 その）public/customersを作成していないため、顧客のマイページへの移動不可能
    # そのため一時的にtopページへの移動させています
    # public/customersを作成後に下記訂正予定
    # ↓10／23pathの後ろの(resource)を削除しました。urlにmy_page.1と表示されるため（しま）
    # 10/26マイページからトップページに飛ぶように設定しました。（りんたろう）
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    customers_my_page_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postcode,:address,:telephone_number])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def converting_to_jpy(unit_price)
    "#{unit_price.to_s(:delimited, delimiter: ',')}円"
  end

end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  	<div style='margin: 20px 40px 40px 40px;'>
    	<div>
    		<p class="text-center mr-3">@NAGANO_CAKE</p>
    	</div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top bg-danger bg-opacity-75">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
       <a class="navbar-brand" href="/"><%= image_tag 'logo.jpg', size: '63x63', class: 'ml-5' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <% if request.fullpath.include? "/admin" %>
            <li class='mx-1'>
              <%= link_to admin_items_path,class: 'btn btn-outline-light' do %>商品一覧<% end %>
            </li>
            <li class='mx-1'>
              <%= link_to admin_customers_path,class: 'btn btn-outline-light' do %>会員一覧<% end %>
            </li>
            <li class='mx-1'>
              <%=  link_to admin_root_path,class: 'btn btn-outline-light' do %>注文履歴一覧<% end %>
            </li>
            <li class='mx-1'>
              <%=  link_to admin_genres_path,class: 'btn btn-outline-light' do %>ジャンル一覧<% end %>
            </li>
            <li class='mx-1'>
              <%= link_to destroy_admin_session_path, method: :delete,class: 'btn btn-outline-light' do %>ログアウト<% end %>
            </li>
          <% else %>
            <li class="my-auto pr-5 mr-5 text-light">
              現在、管理者アカウントでログインしています。
            </li>
            <li class='mx-1'>
              <%= link_to customers_my_page_path,class: 'btn btn-outline-light' do %>マイページ<% end %>
            </li>
            <li class='mx-1'>
              <%=  link_to items_path,class: 'btn btn-outline-light' do %>商品一覧<% end %>
            </li>
            <li class='mx-1'>
              <%=  link_to cart_items_path,class: 'btn btn-outline-light' do %>カート<% end %>
            </li>
            <li class='mx-1'>
              <%= link_to destroy_customer_session_path, method: :delete,class: 'btn btn-outline-light' do %>ログアウト<% end %>
            </li>
          <% end %>

        <% elsif customer_signed_in? %>
          <li class="my-auto pr-5 mr-5 text-light">
            ようこそ、<%= current_customer.last_name %>さん！
          </li>

          <li class='mx-1'>
            <%= link_to customers_my_page_path,class: 'btn btn-outline-light' do %>マイページ<% end %>
          </li>
          <li class='mx-1'>
            <%=  link_to items_path,class: 'btn btn-outline-light' do %>商品一覧<% end %>
          </li>
          <li class='mx-1'>
            <%=  link_to cart_items_path,class: 'btn btn-outline-light' do %>カート<% end %>
          </li>
          <li class='mx-1'>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'btn btn-outline-light' do %>ログアウト<% end %>
          </li>

        <% else %>

          <li class='mx-1'>
            <%= link_to about_path,class: 'btn btn-outline-light' do %>
              About
            <% end %>
          </li>
          <li class='mx-1'>
            <%= link_to items_path,class: 'btn btn-outline-light' do %>商品一覧<% end %>
          </li>
          <li class='mx-1'>
            <%= link_to new_customer_registration_path,class: 'btn btn-outline-light' do %>新規登録<% end %>
          </li>
          <li class='mx-1'>
            <%= link_to new_customer_session_path ,class: 'btn btn-outline-light' do %>ログイン<% end %>
          </li>
        <% end %>

        </ul>

      </div>

    </div>
      <form class="d-flex">
        <input class="form-control" type="search" placeholder="文字を入力" aria-label="Search">
        <button class="btn bg-warning ml-2" type="submit">Search</button>
      </form>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= render 'layouts/header' %>
  <body class='pt-5 mt-5'>
      <main class='pb-5'>
        <%= yield %>
      </main>
  </body>
   <%= render 'layouts/footer' %>
</html>